name: "CI"
on:
  push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install xh
        run: |
          curl -sfL https://raw.githubusercontent.com/ducaale/xh/master/install.sh | sh
      - name: Validate schema
        run: |
          bash validate-schema.sh
        env:
          SCHEMA_REGISTRY_TOKEN: ${{ secrets.SCHEMA_REGISTRY_TOKEN }}
