name: "Validate schema"
on:
  push

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install xh
        run: |
          curl -L -o xh.tar.gz https://github.com/ducaale/xh/releases/download/v0.16.0/xh-v0.16.0-x86_64-unknown-linux-musl.tar.gz
          tar xzf xh.tar.gz && mkdir -p "$HOME"/.local/bin/
          sudo mv xh-*/xh "$HOME"/.local/bin/
          chmod +x "$HOME"/.local/bin/xh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Validate
        run: |
          ./schema.sh validate
        env:
          SCHEMA_REGISTRY_TOKEN: ${{ secrets.SCHEMA_REGISTRY_TOKEN }}
